apollo:
  bootstrap:
    enabled: true
    # will inject 'application' and 'TEST1.apollo' namespaces in bootstrap phase
    namespaces: application,application.yml
server:
#  port: 8092
  connection-timeout: 180000
#注册客户端配置
eureka:
  instance:
    #心跳间隔时间
    lease-renewal-interval-in-seconds: 10
    #告诉服务端多久未收到心跳则认为该服务关闭
    lease-expiration-duration-in-seconds: 20
    prefer-ip-address: true
  client:
    #定时刷新本地缓存
    #registry-fetch-interval-seconds: 5
    enabled: true
    service-url:
      defaultZone: http://admin:admin@localhost:8080/eureka/
spring:
  #应用信息
#  application:
#    name: service-order
  # 异常处理
  mvc:
    throw-exception-if-no-handler-found: true
  #当遇到同样名字的时候，是否允许覆盖注册(seata与feign中有一个bean命名冲突"feignHystrixBuilder")
  main:
    allow-bean-definition-overriding: true
  resources:
    add-mappings: false
  #redis 连接配置
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 5000ms  # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 8   # 连接池最大连接数（使用负值表示没有限制）
        max-wait:   1ms   # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle:   8   # 连接池中的最大空闲连接
        min-idle:   0   # 连接池中的最小空闲连接
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: yzzy65203
    #druid相关配置
    druid:
      #监控统计拦截的filters
      #      filters: stat
      #配置初始化大小/最小/最大
      initialSize: 1
      minIdle: 1
      maxActive: 20
      #获取连接等待超时时间
      maxWait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
  #zipkin服务链路追踪
  zipkin:
    sender:
      #设置链路消息传递方式
      type: rabbit
    #设置zipkin地址
    base-url: http://localhost:9411
  #zipkin采样比例
  sleuth:
    sampler:
      probability: 1.0
  #rabbitmq配置
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  #seata 事务管理组名
  cloud:
    alibaba:
      seata:
        tx-service-group: sandhouse_test
#Hystrix断路器
feign:
  hystrix:
    enabled: true
#actuator监控检查配置
management:
  endpoints:
    web:
      exposure:
        #加载端点类型
        include: "*"
  endpoint:
    health:
      #健康信息细节显示策略
      show-details: ALWAYS
#hystrix设置隔离策略为信号量模式(如不开启,则RequestInterceptor中无法取到request)
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE